language: node_js
node_js:
  - "10"

cache: yarn

addons:
  chrome: stable

# Define environment variables
env:
  - secure: "JMpsHaV3yrtMcJswXY7+rTkj7j+PlGmS3px+GzzhnrgUDfcp7UPlSnw8PWXUiO1MaQuclStpvLECIeDWDeQODoFVLyivu6V8jd3nz16OEjlG968Sh9zkMqW7xamzZRxYcOivy3/oCtnsiPNRrlQx7zAhXcR38yVectbfoCBEFFvU9M0CE53DTuHsjfC4Z116ONFIboFzMZ2tojCFOpAeg7TfhUjIIVdNtuTjdHESyqrwtOwQGRubHmejTTjWb/VCMMEAvoZ9REhdrHkKve7jTjgIjG3wyyaBfEDhw6S2yc6/U83zJuKz3paa8oosv3UTVtpYj11UN+E83XSR9vrdyr7dG9U27BilnDUcaZwt/dpHqlbvJXb24HFxi5eG5JOrqdnHx2fuSkHQvQ7Gs+rcaMaPJx/LC0bMAbhm9iF9zHbOfJd0n83w4zPSqVzwTxKYvbiek79OzsMrbG5dwvBwbv9vuIgn1IjqOtJkJNWLDbXAjQDj53jNHiNDQ6ONcLUDZUv3+vSR3qTRAvDuP6vHPru7MdxQ0YjzgPUPV1sW3mDBEGaIGYyrBAiN59aI/tUtQHbC0pK1fOSK9mQGN6JH17fQrv/JmOJqQoKSGdpsaUVuvro/D9bygQizXzfD5fUFc+AYQDY0+iPGV63s09cmFaX2Of3+w0VrQj+MITmK7cc="

git:
  depth: false

install:
  - yarn global add @angular/cli
  - yarn install
  - ./get-info.sh

jobs:
    include:
        - stage: test
          if: (NOT branch =~ /^release\/.*$/) AND tag IS NOT present
          script: yarn run lint && yarn run test
          fast_finish: true
        - stage: deploy
          if: branch = dev AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh test
        - stage: deploy
          if: branch =~ /^release\/.*$/ AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh stage
        - stage: deploy
          if: tag IS present AND tag =~ /^deploy.*$/ AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh dev
        - stage: deploy
          if: tag IS present AND tag =~ /^v.*$/ AND NOT type = "pull_request"
          before_install:
              - sudo apt-get install python3-pip python3-setuptools
              - pip3 install awscli --upgrade
          script: ./build-deploy.sh prod && ./build-deploy.sh demo
